const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const foods={Breakfast:[['Eggs',2,144,13,1,10],['Banana',1,105,1,27,0]],Lunch:[['Chicken breast',150,248,47,0,5],['Rice',1,205,4,45,0],['Vegetables',1,70,3,12,0]],Snack:[['Guava',1,68,3,14,1]],Dinner:[['Tilapia',150,192,39,0,4],['Rice',1,205,4,45,0],['Vegetables',1,70,3,12,0]]};
const defaults={name:'Toki',age:30,gender:'male',height:173,startWeight:89,goalWeight:73,activityLevel:1.375,calorieGoalType:'normal',customCalorieTarget:'',waterGoal:3,stepGoal:7000,weights:[],meals:{},exercises:{},dailyLogs:{},groceries:['Eggs','Chicken','Rice','Fish','Banana','Guava','Vegetables','Chickpeas'].map(name=>({name,done:false})),days:{}};
let data=Object.assign({},defaults,JSON.parse(localStorage.getItem('fitday-data')||'{}'));for(const k of ['weights','meals','exercises','dailyLogs','groceries','days'])data[k]=data[k]||defaults[k];
const today=new Date().toISOString().slice(0,10);let day=Object.assign({water:0,steps:0},data.days[today]||{});
const fmt=n=>new Intl.NumberFormat().format(Math.round(n));const kg=n=>`${Number(n).toFixed(1)} kg`;const dateLabel=d=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'));
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function latestWeight(){return data.weights.at(-1)?.weight||Number(data.startWeight)||0}
function calculateBMR(weight=latestWeight()){let base=10*weight+6.25*Number(data.height)-5*Number(data.age);return Math.round(base+(data.gender==='female'?-161:5))}
function calculateTDEE(bmr=calculateBMR()){return Math.round(bmr*Number(data.activityLevel))}
function goalAdjustment(){return({maintain:0,mild:250,normal:500,aggressive:750})[data.calorieGoalType]??0}
function targetCalories(tdee=calculateTDEE()){return data.calorieGoalType==='custom'?Number(data.customCalorieTarget)||0:Math.max(500,tdee-goalAdjustment())}
function mealTotals(date=today){let out={c:0,p:0,carb:0,f:0},offset=0;Object.values(foods).flat().forEach(x=>{if(data.meals[date+'-'+offset]){out.c+=x[2];out.p+=x[3];out.carb+=x[4];out.f+=x[5]}offset++});return out}
function exerciseTotal(date=today){return(data.exercises[date]||[]).reduce((sum,x)=>sum+Number(x.calories),0)}
function currentMetrics(){let weight=latestWeight(),food=mealTotals(),exercise=exerciseTotal(),bmr=calculateBMR(weight),tdee=calculateTDEE(bmr),target=targetCalories(tdee),net=food.c-exercise,deficit=tdee-net;return{date:today,weight,bmr,tdee,target,food:food.c,protein:food.p,carbs:food.carb,fat:food.fat,exercise,net,deficit,fatLoss:deficit/7700}}
function saveSnapshot(){let m=currentMetrics();data.dailyLogs[today]={...m,exercises:(data.exercises[today]||[]).map(x=>({...x}))};data.days[today]=day;localStorage.setItem('fitday-data',JSON.stringify(data))}
function persist(){saveSnapshot()}
function hasProfile(){return Number(data.age)>0&&Number(data.height)>0&&latestWeight()>0}
function renderMeals(){let offset=0;$('#meal-list').innerHTML=Object.entries(foods).map(([meal,items])=>`<section class="card meal-card"><div class="section-title"><h2>${meal}</h2><span class="pill">${items.reduce((a,x)=>a+x[2],0)} kcal</span></div>${items.map(x=>{const id=today+'-'+offset++;return `<label class="food-row"><input type="checkbox" data-food="${id}" ${data.meals[id]?'checked':''}><div><b>${x[0]}</b><small>${x[1]} serving${x[1]>1?'s':''} · ${x[2]} kcal</small></div><b>${x[3]}g protein</b></label>`}).join('')}</section>`).join('');$$('[data-food]').forEach(el=>el.onchange=()=>{data.meals[el.dataset.food]=el.checked;persist();render()})}
function renderExercise(){let items=data.exercises[today]||[];$('#exercise-total').textContent=`${fmt(exerciseTotal())} kcal burned`;$('#exercise-list').innerHTML=items.length?items.map((x,i)=>`<div class="exercise-row"><span class="exercise-icon">⌁</span><div><b>${escapeHtml(x.name)}</b><small>${x.duration} min · ${fmt(x.calories)} kcal burned</small></div><button class="delete-item" data-exercise-delete="${i}" aria-label="Delete exercise">×</button></div>`).join(''):'<p class="empty-state">No activity logged yet. A walk counts.</p>';$$('[data-exercise-delete]').forEach(b=>b.onclick=()=>{data.exercises[today].splice(Number(b.dataset.exerciseDelete),1);persist();render()})}
function escapeHtml(value){const e=document.createElement('div');e.textContent=value;return e.innerHTML}
function spark(svgId,emptyId,values){let svg=$(svgId),empty=$(emptyId);if(values.length<2){svg.innerHTML='';empty.hidden=false;return}empty.hidden=true;let min=Math.min(...values),max=Math.max(...values),range=max-min||1,coords=values.map((v,i)=>`${10+i/(values.length-1)*300},${115-(v-min)/range*93}`).join(' ');svg.innerHTML=`<line x1="0" y1="120" x2="320" y2="120"/><polyline points="${coords}"/>${coords.split(' ').map(p=>{let[a,b]=p.split(',');return`<circle cx="${a}" cy="${b}" r="4"/>`}).join('')}`}
function renderProgress(){let weight=latestWeight(),bmi=data.height?(weight/(data.height/100)**2).toFixed(1):'—';$('#bmi-value').textContent=bmi;let logs=Object.values(data.dailyLogs),totalDeficit=logs.reduce((s,x)=>s+Math.max(0,x.deficit||0),0),fat=totalDeficit/7700;$('#fat-loss-value').textContent=totalDeficit?`${fat.toFixed(1)} kg`:'—';let avgDeficit=logs.length?totalDeficit/logs.length:0,predict=weight-(avgDeficit*30/7700);$('#prediction-value').textContent=logs.length?kg(predict):'—';spark('#weight-chart','#chart-empty',data.weights.slice(-8).map(x=>x.weight));let last7=Object.values(data.dailyLogs).sort((a,b)=>a.date.localeCompare(b.date)).slice(-7);spark('#deficit-chart','#deficit-empty',last7.map(x=>x.deficit));$('#average-deficit').textContent=last7.length?`${fmt(last7.reduce((s,x)=>s+x.deficit,0)/last7.length)} kcal avg`:'— avg';let month=today.slice(0,7),monthLogs=logs.filter(x=>x.date.startsWith(month)),sum=k=>monthLogs.reduce((s,x)=>s+(x[k]||0),0),days=monthLogs.length||1;$('#monthly-summary').innerHTML=[[fmt(sum('food')),'FOOD KCAL'],[fmt(sum('exercise')),'BURNED'],[fmt(sum('food')/days),'AVG INTAKE'],[fmt(sum('deficit')/days),'AVG DEFICIT'],[(sum('deficit')/7700).toFixed(1)+' kg','EST. FAT LOSS'],[monthLogs.length,'DAYS LOGGED']].map(x=>`<div><b>${x[0]}</b><small>${x[1]}</small></div>`).join('');$('#history-list').innerHTML=logs.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,14).map(x=>`<div class="history-row"><div><b>${dateLabel(x.date)}</b><small>${kg(x.weight)} · BMR ${fmt(x.bmr)}</small></div><div><b class="${x.deficit>=0?'positive':'negative'}">${x.deficit>=0?'−':'+'}${fmt(Math.abs(x.deficit))} kcal</b><small>${fmt(x.food)} food · ${fmt(x.exercise)} burned</small></div></div>`).join('')||'<p class="empty-state">Daily snapshots will appear as you track.</p>'}
function renderGrocery(){$('#grocery-list').innerHTML=data.groceries.map((g,i)=>`<label class="grocery-row ${g.done?'done':''}"><input type="checkbox" data-grocery="${i}" ${g.done?'checked':''}><span>${escapeHtml(g.name)}</span><button class="delete-item" data-delete="${i}" aria-label="Delete">×</button></label>`).join('');$$('[data-grocery]').forEach(e=>e.onchange=()=>{data.groceries[e.dataset.grocery].done=e.checked;persist();renderGrocery()});$$('[data-delete]').forEach(e=>e.onclick=()=>{data.groceries.splice(Number(e.dataset.delete),1);persist();renderGrocery()})}
function render(){let m=currentMetrics(),under=m.food<=m.target,ratio=m.target?m.food/m.target:0;$('#greeting').textContent=`Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, ${data.name}`;$('#date-label').textContent=new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#calories-eaten').textContent=fmt(m.food);$('#calorie-ring').className=`ring ${ratio>1?'over':ratio>.85?'near':''}`;$('#calorie-ring').style.background=`conic-gradient(var(--ring, #d7f1e2) ${Math.min(100,ratio*100)}%,transparent 0)`;$('#deficit-head').textContent=hasProfile()?`${m.deficit>=0?'−':'+'}${fmt(Math.abs(m.deficit))} kcal`:'—';$('#deficit-caption').textContent=hasProfile()?m.deficit>=0?'estimated calorie deficit':'estimated calorie surplus':'Complete your profile to calculate it.';$('#dashboard-metrics').innerHTML=[['⚖','WEIGHT',kg(m.weight)],['◎','TARGET',m.target?`${fmt(m.target)} kcal`:'—'],['◉','NET CALORIES',`${fmt(m.net)} kcal`],['♧','EXERCISE',`${fmt(m.exercise)} kcal`]].map(x=>`<article class="metric-card"><span>${x[0]}</span><div><small>${x[1]}</small><b>${x[2]}</b></div></article>`).join('');$('#target-label').textContent=m.target?`${fmt(m.target)} kcal target`:'Set profile';$('#summary-grid').innerHTML=[[fmt(m.bmr),'BMR'],[fmt(m.tdee),'TDEE'],[fmt(m.food),'FOOD'],[fmt(m.exercise),'EXERCISE'],[fmt(m.net),'NET'],[`${m.deficit>=0?'−':'+'}${fmt(Math.abs(m.deficit))}`,'DEFICIT']].map(x=>`<div><b>${x[0]}</b><small>${x[1]}</small></div>`).join('');$('#weekly-loss').textContent=hasProfile()?`At this pace: about ${(Math.max(0,m.deficit)*7/7700).toFixed(2)} kg fat loss per week.`:'Your profile unlocks personal BMR, TDEE, and calorie targets.';$('#water-value').textContent=`${Number(day.water||0).toFixed(2)} L`;$('#water-goal-label').textContent=`${data.waterGoal} L`;$('#steps-value').textContent=fmt(day.steps||0);$('#step-goal-label').textContent=fmt(data.stepGoal);$('#weight-display').textContent=kg(m.weight);let pct=(data.startWeight-data.goalWeight)?Math.max(0,Math.min(100,(data.startWeight-m.weight)/(data.startWeight-data.goalWeight)*100)):0;$('#weight-bar').style.width=pct+'%';$('#goal-progress').textContent=`${Math.round(pct)}% to goal`;$('#weight-caption').textContent=`${Math.max(0,m.weight-data.goalWeight).toFixed(1)} kg to reach your goal of ${data.goalWeight} kg.`;$('#smart-tip').textContent=Number(day.water||0)<data.waterGoal*.6?`You still need ${(data.waterGoal-day.water).toFixed(1)} L of water today.`:m.food>m.target?'You are over your food target today; a gentle walk can help.':m.protein<60?'Try adding an egg or some chicken for protein.':'Your calorie balance looks on track.';$('#nutrition-summary').innerHTML=[[m.food,'CALORIES'],[m.protein+'g','PROTEIN'],[m.carbs+'g','CARBS'],[m.fat+'g','FAT']].map(x=>`<article><b>${x[0]}</b><small>${x[1]}</small></article>`).join('');renderMeals();renderExercise();renderProgress();renderGrocery()}
function initSettings(){let form=$('#settings-form'),fields=['name','age','gender','height','startWeight','goalWeight','activityLevel','calorieGoalType','customCalorieTarget','waterGoal','stepGoal'];fields.forEach(k=>form.elements[k].value=data[k]);const showCustom=()=>$('#custom-target-field').hidden=form.elements.calorieGoalType.value!=='custom';showCustom();form.elements.calorieGoalType.onchange=showCustom;form.onsubmit=e=>{e.preventDefault();for(const k of fields)data[k]=['name','gender','calorieGoalType'].includes(k)?form.elements[k].value:Number(form.elements[k].value);if(data.goalWeight>=data.startWeight)return toast('Goal weight should be below starting weight');if(data.calorieGoalType==='custom'&&!data.customCalorieTarget)return toast('Enter a custom calorie target');persist();render();toast('Profile saved')};$('#theme-toggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('fitday-dark',document.body.classList.contains('dark'))};if(localStorage.getItem('fitday-dark')==='true')document.body.classList.add('dark')}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{$$('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page+'-page').classList.add('active');window.scrollTo(0,0)});$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='water')day.water=Math.min(data.waterGoal,Number(day.water||0)+.25);else{let val=prompt('Today’s steps',day.steps||0);if(val===null)return;day.steps=Math.max(0,Number(val)||0)}persist();render()});$('#save-weight').onclick=()=>{let value=Number($('#weight-input').value);if(value<20||value>300)return toast('Enter a weight between 20 and 300 kg');data.weights=data.weights.filter(x=>x.date!==today);data.weights.push({date:today,weight:value});data.weights.sort((a,b)=>a.date.localeCompare(b.date));persist();$('#weight-input').value='';render();toast('Weight saved; calorie plan updated')};$('#exercise-form').onsubmit=e=>{e.preventDefault();let f=e.currentTarget,x={name:f.name.value.trim(),duration:Number(f.duration.value),calories:Number(f.calories.value)};if(!x.name||x.duration<1||x.calories<1)return toast('Enter a valid exercise');(data.exercises[today]??=[]).push(x);f.reset();persist();render();toast('Exercise added')};$('#add-grocery').onclick=()=>{let i=$('#grocery-input');if(i.value.trim()){data.groceries.push({name:i.value.trim(),done:false});i.value='';persist();renderGrocery()}};$('#grocery-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#add-grocery').click()}};$('#export-data').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='fitday-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#import-data').onchange=e=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{data=Object.assign({},defaults,JSON.parse(reader.result));for(const k of ['weights','meals','exercises','dailyLogs','groceries','days'])data[k]=data[k]||defaults[k];day=Object.assign({water:0,steps:0},data.days[today]||{});initSettings();persist();render();toast('Backup restored')}catch{toast('That file could not be imported')}};reader.readAsText(file)};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');initSettings();persist();render();
