(()=>{
  const style=document.createElement('link');style.rel='stylesheet';style.href='css/live-workout.css';document.head.append(style);
  const key='fitday-live-workout',today=new Date().toISOString().slice(0,10);
  const templates=[['Push-ups','reps',5,15,60],['Sit-ups','reps',4,20,45],['Squats','reps',4,15,45],['Plank','seconds',4,45,60],['Jumping Jacks','reps',4,25,45],['Burpees','reps',3,10,60],['Mountain Climbers','reps',4,20,45],['Pull-ups','reps',3,8,75],['Custom Exercise','reps',3,12,60]];
  let active=null,tick=null;
  const root=()=>document.querySelector('#live-workout-root');
  const read=()=>JSON.parse(localStorage.getItem('fitday-data')||'{}');
  const save=d=>localStorage.setItem('fitday-data',JSON.stringify(d));
  const getActive=()=>JSON.parse(localStorage.getItem(key)||'null');
  const setActive=x=>x?localStorage.setItem(key,JSON.stringify(x)):localStorage.removeItem(key);
  const fmtTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.max(0,s%60)).padStart(2,'0')}`;
  const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function history(){return(read().liveWorkouts||[]).filter(x=>x.date===today).slice(-3).reverse()}
  function ensure(){if(root())return;let heading=document.querySelector('#exercise-page .page-heading');if(!heading)return;heading.insertAdjacentHTML('afterend','<section id="live-workout-root" aria-live="polite"></section><div class="live-modal" id="live-modal" hidden></div>')}
  function render(){ensure();let r=root();if(!r)return;active=getActive();if(active){renderActive();return}let recent=history();r.innerHTML=`<section class="live-intro"><div><p class="eyebrow">GUIDED TRAINING</p><h2>Live workout</h2><p>Follow sets, rest with purpose, and save automatically.</p></div><button id="start-live" class="live-start"><span>▶</span> Start live workout</button></section>${recent.length?`<section class="live-recent"><p class="eyebrow">RECENT WORKOUTS</p>${recent.map(x=>`<div><b>${esc(x.name)}</b><span>${x.sets} sets · ${x.total} ${x.mode==='seconds'?'sec':'reps'} · ${x.calories} kcal</span></div>`).join('')}</section>`:''}`;document.querySelector('#start-live').onclick=openSetup}
  function openSetup(){let modal=document.querySelector('#live-modal');modal.hidden=false;modal.innerHTML=`<div class="live-shade"></div><section class="live-sheet"><div class="live-sheet-head"><div><p class="eyebrow">LIVE WORKOUT</p><h2>Choose your movement</h2></div><button class="live-close" aria-label="Close">×</button></div><div class="template-grid">${templates.map((t,i)=>`<button data-template="${i}">${t[0]}<small>${t[2]} sets · ${t[3]} ${t[1]==='seconds'?'sec':'reps'}</small></button>`).join('')}</div><form id="live-setup" hidden><label>Exercise<input name="name" required></label><div class="live-pair"><label>Sets<input name="sets" type="number" min="1" max="20" required></label><label id="target-label">Reps per set<input name="target" type="number" min="1" max="500" required></label></div><div class="live-pair"><label>Rest <small>seconds</small><input name="rest" type="number" min="0" max="600" required></label><label>Mode<select name="mode"><option value="reps">Reps</option><option value="seconds">Timed hold</option></select></label></div><button class="live-confirm" type="submit">Start workout</button></form></section>`;modal.querySelector('.live-close').onclick=closeSetup;modal.querySelector('.live-shade').onclick=closeSetup;modal.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>chooseTemplate(templates[+b.dataset.template]));}
  function closeSetup(){document.querySelector('#live-modal').hidden=true}
  function chooseTemplate(t){let form=document.querySelector('#live-setup'),f=form.elements;form.hidden=false;f.name.value=t[0];f.sets.value=t[2];f.target.value=t[3];f.rest.value=t[4];f.mode.value=t[1];document.querySelector('#target-label').firstChild.textContent=t[1]==='seconds'?'Seconds per set':'Reps per set';f.mode.onchange=()=>document.querySelector('#target-label').firstChild.textContent=f.mode.value==='seconds'?'Seconds per set':'Reps per set';form.onsubmit=e=>{e.preventDefault();start({name:f.name.value.trim(),sets:+f.sets.value,target:+f.target.value,rest:+f.rest.value,mode:f.mode.value})}}
  function start(plan){if(!plan.name||plan.sets<1||plan.target<1)return;active={...plan,date:today,set:1,value:0,completed:0,phase:'work',started:Date.now(),restUntil:0};setActive(active);closeSetup();if(navigator.vibrate)navigator.vibrate(10);render()}
  function elapsed(){return Math.floor((Date.now()-active.started)/1000)}
  function renderActive(){clearInterval(tick);let r=root(),pct=active.completed/active.sets*100,unit=active.mode==='seconds'?'sec':'reps',remaining=active.sets-active.completed; if(active.phase==='rest'){renderRest();return}r.innerHTML=`<section class="live-active"><div class="live-active-head"><div><p class="eyebrow">${esc(active.name).toUpperCase()}</p><h2>Set ${active.set} <span>/ ${active.sets}</span></h2></div><button id="end-live" class="live-end">End</button></div><div class="energy-orb" style="--orb:${pct}%"><div><b>${Math.round(pct)}%</b><small>complete</small></div></div><div class="live-target"><strong id="live-count">${active.value}</strong><span>/ ${active.target} ${unit}</span></div><div class="live-controls"><button data-add="1">+1</button><button data-add="5">+5</button><button id="undo-live">Undo</button></div><button id="complete-set" class="complete-set" ${active.value<active.target?'disabled':''}>${active.value<active.target?`${active.target-active.value} ${unit} remaining`:'Complete set'}</button><div class="live-stats"><span><b>${fmtTime(elapsed())}</b>elapsed</span><span><b>${active.completed}</b>sets done</span><span><b>${remaining}</b>remaining</span><span><b>${estimateCalories()}</b>kcal est.</span></div></section>`;r.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{active.value=Math.min(active.target,active.value+(+b.dataset.add));pulse();setActive(active);renderActive()});r.querySelector('#undo-live').onclick=()=>{active.value=Math.max(0,active.value-1);setActive(active);renderActive()};r.querySelector('#complete-set').onclick=completeSet;r.querySelector('#end-live').onclick=endWorkout;tick=setInterval(()=>{let e=r.querySelector('.live-stats span:first-child b');if(e)e.textContent=fmtTime(elapsed())},1000)}
  function pulse(){if(navigator.vibrate)navigator.vibrate(8)}
  function completeSet(){if(active.value<active.target)return;active.completed++;active.value=0;if(navigator.vibrate)navigator.vibrate([12,30,18]);if(active.completed>=active.sets){finish();return}active.set++;active.phase='rest';active.restUntil=Date.now()+active.rest*1000;setActive(active);renderRest()}
  function renderRest(){clearInterval(tick);let r=root();r.innerHTML=`<section class="live-active rest-mode"><p class="eyebrow">SET ${active.completed} COMPLETE</p><h2>Rest and reset</h2><div class="rest-clock"><b id="rest-time">${fmtTime(Math.ceil((active.restUntil-Date.now())/1000))}</b><span>until set ${active.set}</span></div><div class="rest-actions"><button id="skip-rest">Skip rest</button><button id="add-rest">+15 sec</button></div><p class="rest-message">${active.completed===active.sets-1?'One more set.':'Good work. Your next set is ready soon.'}</p></section>`;let update=()=>{let s=Math.ceil((active.restUntil-Date.now())/1000);let e=document.querySelector('#rest-time');if(e)e.textContent=fmtTime(s);if(s<=0){clearInterval(tick);active.phase='work';setActive(active);renderActive()}};r.querySelector('#skip-rest').onclick=()=>{active.phase='work';setActive(active);renderActive()};r.querySelector('#add-rest').onclick=()=>{active.restUntil+=15000;setActive(active);update()};tick=setInterval(update,500)}
  function estimateCalories(){return Math.max(1,Math.round((active.completed+(active.value/active.target))*4))}
  function endWorkout(){if(!confirm('End this workout? Your completed sets will be saved.'))return;if(active.completed)finish();else{setActive(null);render()}}
  function finish(){clearInterval(tick);let seconds=elapsed(),calories=estimateCalories(),d=read();d.exercises=d.exercises||{};d.liveWorkouts=d.liveWorkouts||[];let total=active.completed*active.target;d.exercises[today]=d.exercises[today]||[];d.exercises[today].push({name:active.name,duration:Math.max(1,Math.round(seconds/60)),calories});d.liveWorkouts.push({id:Date.now(),date:today,name:active.name,sets:active.completed,total,mode:active.mode,duration:seconds,calories});save(d);let r=root();r.innerHTML=`<section class="live-complete"><div class="complete-orb">✓</div><p class="eyebrow">WORKOUT COMPLETE</p><h2>Strong finish.</h2><p>${active.completed} sets · ${total} ${active.mode==='seconds'?'seconds':'reps'} · ${calories} kcal</p><button id="done-live" class="live-confirm">Done</button></section>`;if(navigator.vibrate)navigator.vibrate([15,45,15,45,25]);setActive(null);r.querySelector('#done-live').onclick=()=>{render();location.reload()}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();window.addEventListener('storage',render);
})();
